const themes = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
  "dim",
  "nord",
  "sunset",
];

const themeColor = {
  light: "#ffffff",
  dark: "#3b424e",
  cupcake: "#faf7f5",
  bumblebee: "#ffffff",
  emerald: "#ffffff",
  corporate: "#ffffff",
  synthwave: "#2c1a65",
  retro: "#e4d8b4",
  cyberpunk: "#ffee00",
  valentine: "#f0d6e8",
  halloween: "#1f1f1f",
  garden: "#e9e7e7",
  forest: "#171212",
  aqua: "#0c25b6",
  lofi: "#ffffff",
  pastel: "#ffffff",
  fantasy: "#ffffff",
  wireframe: "#ffffff",
  black: "#000000",
  luxury: "#ffffff",
  dracula: "#302f3d",
  cmyk: "#ffffff",
  autumn: "#f6ad55",
  business: "#f6ad55",
  acid: "#f6ad55",
  lemonade: "#f6ad55",
  night: "#f6ad55",
  coffee: "#f6ad55",
  winter: "#f6ad55",
  dim: "#f6ad55",
  nord: "#f6ad55",
  sunset: "#f6ad55",
};

const featureTwo = [
  {
    id: 1,
    title: "Say Anything",
    img: "/images/features/feature-two-1.png",
    description:
      "Chat for free. Celestia uses your devices's data connection so you can avoid SMS and MMS fees.",
  },
  {
    id: 2,
    title: "Speak Freely",
    img: "/images/features/feature-two-2.png",
    description:
      "Make safe and secure conversations with people who live across town, or across the ocean, with no long-distance charges.",
  },
  {
    id: 3,
    title: "Make Privacy Stick",
    img: "/images/features/feature-two-3.png",
    description:
      "Add a new layer of privacy to your conversations with Celestia's end-to-end encryption.",
  },
  {
    id: 4,
    title: "Make Privacy Stick",
    img: "/images/features/feature-two-4.png",
    description:
      "Group chats make it easy to stay connected to your family, friends, and co-workers no matter where they are.",
  },
];

export { themes, themeColor, featureTwo };
